### ISSUE TITLE
Double Shield bug 

### ISSUE THREAD

**Issue by Willtom999** [JavierLeon9966/Shield#10]
![B1442E16-1EB3-4613-AD52-592C0E391486](https://user-images.githubusercontent.com/83521998/145719024-4166c78c-0460-4599-ae5c-ae01623c29fc.png)

**Comment by Willtom999** [comment]
Is pm4

**Comment by JavierLeon9966** [comment]
This is a PocketMine-MP bug, is already known that some times items may duplicate or appear in the wrong order. You should report this to PocketMine-MP
