### ISSUE TITLE
Duplicate shield in inventory (PM 5.0.0-BETA1)

### ISSUE THREAD

**Issue by GH-PM** [JavierLeon9966/Shield#19]
![dp](https://user-images.githubusercontent.com/127597296/224495116-5b3751e6-fb97-469b-aa63-3e0f21722547.png)
Using the last ver

**Comment by JavierLeon9966** [comment]
Fixed by https://github.com/JavierLeon9966/Shield/commit/b4fe70578ed05c4c7533c7fb39a1a64b69b3a183
